services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: saiko_postgres
    restart: always
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=mysecurepassword
      - POSTGRESQL_DATABASE=mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
